# Generated by Django 5.0.1 on 2024-01-26 05:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('retailer', models.CharField(max_length=100)),
                ('purchaseDate', models.DateField()),
                ('purchaseTime', models.TimeField()),
                ('total', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Value must be in the format '123.45'", regex='^\\d+\\.\\d{2}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Value must be in the format '123.45'", regex='^\\d+\\.\\d{2}$')])),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.purchase')),
            ],
        ),
    ]
